name: Android Release Build
on:
  push:
    branches: main
    tags:
      - v*
permissions:
  contents: write

jobs:
  release_build:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Generate cache key
        run: ./scripts/checksum.sh . checksum.txt

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build Release apk
        env:
          GT_USERNAME: ${{ github.actor }}
          GT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew app:assembleProdRelease

      - name: Build Release bundle
        env:
          GT_USERNAME: ${{ github.actor }}
          GT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew app:bundleProdRelease

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: |
            app/build/outputs/apk/**/release/*.apk
            app/build/outputs/bundle/*Release/*.aab