name: Display Coverage

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit_test_coverage:
    runs-on: macos-latest
    strategy:
      matrix:
        module: [ network, data ]

    permissions:
      contents: write
      pull-requests: write
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run local tests for the combined coverage report
        run: ./gradlew core:${{ matrix.module }}:testStagingDebugUnitTest

      - name: Generate coverage reports for Staging variants
        env:
          GT_USERNAME: ${{ github.actor }}
          GT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew core:${{ matrix.module }}:createStagingDebugCombinedCoverageReport

      - name: Display local test coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: Test coverage report in ${{ matrix.module }} module
          min-coverage-overall: 30
          min-coverage-changed-files: 60
          paths: |
            ./core/${{ matrix.module }}/build/reports/jacoco/**/*Report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true