name: Push to Firebase App Distribution
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write

jobs:
  release_build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Grant Permission
        run: chmod +x ./scripts/update_version_code.sh

      - name: Set versionCode as environment variable
        run: |
          VERSION_CODE=${GITHUB_RUN_NUMBER}
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "Set versionCode to $VERSION_CODE"

      - name: Update Version Code
        run: |
          ./scripts/update_version_code.sh versionCode $VERSION_CODE

      - name: Read Version Name info enviroment variable
        run: |
          VERSION_NAME=$(grep -E "^versionName" configs/version_info.properties | cut -d '=' -f2 | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Echo VersionInfo
        run: cat configs/version_info.properties

      - name: Install GMD image for baseline profile generation
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager "system-images;android-33;aosp_atd;x86_64"

      - name: Accept Android licenses
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Build release variant
        run: ./gradlew app:bundleProdRelease
          -Pandroid.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile
          -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
          -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true
          -Pandroid.experimental.androidTest.numManagedDeviceShards=1
          -Pandroid.experimental.testOptions.managedDevices.maxConcurrentDevices=1

      - name: Find APP File
        id: find_output
        run: |
          app_file=$(find ./app -name "*.aab" | head -n 1)
          echo "APP_FILE=${app_file}" >> $GITHUB_ENV

      - name: Upload App file
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: internal
          file: ${{ env.APP_FILE }}

      - name: Send Slack Notification
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              text: "Hi, EasyAi(${{ env.VERSION_NAME }}) has uploaded to Firebase Distribution :tada: \n",
              attachments: [{
                "author_name": "${{ github.actor }}",
                "author_link": "https://github.com/${{ github.actor }}",
                "author_icon": "https://github.com/${{ github.actor }}.png?size=32",
                color: 'good',
                fields: [{
                     title: "Build Version",
                     value: "${{ env.VERSION_NAME }}",
                     short: true
                 },
                 {
                     title: "Release Notes",
                     value: "```We made improvements and upgrade Gemini Model```",
                     short: false
                }],
                "footer": "EasyOrg"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}