name: upload codecov

on: [push, pull_request]

jobs:
  prepare:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Generate cache key
        run: ./scripts/checksum.sh . checksum.txt

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

  unit_test_report:
    needs: prepare
    runs-on: macos-latest
    strategy:
      matrix:
        module: [ network, data ]
    steps:
      - name: run unit test report
        env:
          GT_USERNAME: ${{ github.actor }}
          GT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew core:${{ matrix.module }}:jacocoTestReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.module }}
          files: ./core/${{ matrix.module }}/build/reports/jacoco/jacocoTestStagingDebugUnitTestReport/jacocoTestStagingDebugUnitTestReport.xml
